#!/bin/sh
wget http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo -O /etc/yum.repos.d/virtualbox.repo
yum -y install gcc kernel-devel VirtualBox-3.2 && usermod -a -G vboxusers profalbert
